name: Changelog Update

on:
  pull_request:
    types: [opened, labeled]
    branches:
      - main
      - 6.x

jobs:
  update-changelog:
    name: Update Changelog
    uses: alexcams/.github/.github/workflows/update-changelog.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
